server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    com.skim: DEBUG

securityProvider:
  securities:   # securities to use by default
    - COF
    - GOOGL
    - MSFT
  startDate: 2017-01-01 # start date range for fetching daily prices
  endDate: 2017-06-30   # end date range for fetching daily prices
  busyDayThreshold: 10  # percentage value greater than avg daily security volume

quandl:
  uri: https://www.quandl.com
  apiKey: s-GMZ_xkw6CrkGYUWs1p
  databaseCode: WIKI
  jerseyClient:
    timeout: 3000ms
    connectionTimeout: 3000ms
    gzipEnabled: true
    gzipEnabledForRequests: true

  #Cache settings